### PR TITLE
Fixes to enabling replicating RFC Editor changes in Markdown

### PR DESCRIPTION
**Pull request by str4d**

### CODE REVIEW

**Comment by miekg** [comment]
rfc 7991 is almost _not_ used in current day xml2rfc, so I'm wondering how these changes map to ouput?

Do you have an example of wrong output which now is good output?

PR description and or commit mesg. don't tell me

**Comment by str4d** [comment]
The three commit messages reference the issues that explain the corresponding problems, and in the case of the references section provides example Markdown that renders bad before this PR and good after. I didn't provide example Markdown for the other two because their issues seemed obvious from the description, but I can add examples there if desired (which would just be a title section with the relevant attribute).

If there's a particular style you prefer for contributed PRs, I couldn't find documentation in the repo for it.

**Comment by miekg** [comment]
checked locally, lgtm

but test failure

**Comment by miekg** [comment]
needs these patches:
~~~
diff --git render/mhtml/hook.go render/mhtml/hook.go
index 5b0d3f1..29b665b 100644
--- render/mhtml/hook.go
+++ render/mhtml/hook.go
@@ -29,7 +29,9 @@ func (r RendererOptions) RenderHook(w io.Writer, node ast.Node, entering bool) (
                }
                io.WriteString(w, `<h1 id="footnote-section">`)
                io.WriteString(w, r.Language.Footnotes())
-       case *mast.Bibliography:
+               // TODO(miek): why no ast.GoToNext here? Oversight?
+       case *mast.BibliographyWrapper, *mast.Bibliography:
+               // TODO(miek): open a new section for the Wrapper variant?
                if !entering {
                        io.WriteString(w, "</dl>\n")
                        return ast.GoToNext, true
~~~
and:
~~~
diff --git render/man/renderer.go render/man/renderer.go
index b6770b5..917b2bb 100644
--- render/man/renderer.go
+++ render/man/renderer.go
@@ -441,7 +441,7 @@ func (r *Renderer) RenderNode(w io.Writer, node ast.Node, entering bool) ast.Wal
                r.Title = node // save for later.
        case *mast.Authors:
                r.authors(w, node, entering)
-       case *mast.Bibliography:
+       case *mast.Bibliography, *mast.BibliographyWrapper:
                if entering {
                        r.outs(w, "\n.SH \"")
                        r.outs(w, strings.ToUpper(r.opts.Language.Bibliography()))
~~~

**Comment by miekg** [comment]
I'll add this

**Pull request merged**
